### ISSUE TITLE
Create an `Adding Scripts` page on the documentation

### ISSUE THREAD

**Issue by TeaganKing** [NCAR/CUPiD#74]
This should be complimentary to the current `Adding Documentation` page.

**Comment by rmshkv** [comment]
Since I haven't gotten this page written yet, here's a quick example of how a scripts block in the config.yml should look:
```
compute_scripts:
    ocean:
        test_script:
            parameter_groups:
                none: {}
            product:
                "nothing.txt"
```
This should be on the same level as compute_notebooks, and follows the same component categories as compute_notebooks (once that PR goes in). The script this is running is `test_script.py` and arguments can be put under parameter_groups. Due to how Ploomber works it's required to generate an output file, which you specify under the required "product" key. Ploomber will check if that file exists before trying to run the script, similarly to how it does caching for notebooks.
