### ISSUE TITLE
/glade/scratch

### ISSUE THREAD

**Issue by dabail10** [NCAR/CUPiD#81]
**Describe the bug**
The /glade/scratch partition is not available and at least one of the notebooks points there.

**To Reproduce**
cupid-run config.yml

**Expected behavior**
The following message:

PermissionError: [Errno 13] Permission denied: '/glade/scratch'

ploomber.exceptions.TaskBuildError: Error when executing task 'ocean_surface'. Partially executed notebook available at /glade/u/home/dbailey/CUPiD/examples/coupled_model/computed_notebooks/quick-run/ocean_surface.ipynb
ploomber.exceptions.TaskBuildError: Error building task "ocean_surface"
===================================================== Summary (1 task) =====================================================
NotebookRunner: ocean_surface -> File('computed_notebook...cean_surface.ipynb')
===================================================== DAG build failed =====================================================

**Additional context**
There are a number of paths hard coded to /glade/scratch in mom-tools.

**Comment by mnlevy1981** [comment]
I think the issue is that `mom6-tools` uses `ncar-jobqueue`, and the default configuration for that package points to `/glade/scratch/`. Do you have a `~/.config/dask/ncar-jobqueue.yaml` file on glade? If so, there's probably a block like

```yaml
casper-dav:
  pbs:
    #    project: XXXXXXXX
    name: dask-worker-casper-dav
    cores: 1 # Total number of cores per job
    memory: '10GB' # Total amount of memory per job
    processes: 1 # Number of Python processes per job
    interface: ext
    walltime: '01:00:00'
    resource-spec: select=1:ncpus=1:mem=25GB
    queue: casper
    log-directory: '/glade/derecho/scratch/${USER}/dask/casper-dav/logs'
    local-directory: '/glade/derecho/scratch/${USER}/dask/casper-dav/local-dir'
    job-extra: []
    env-extra: []
    death-timeout: 60
```

Where I've already updated `log-directory` and `local-directory` to use `/glade/derecho/scratch` but your version may specify `/glade/scratch` instead. Another place to look is `~/.dask/jobqueue.yaml`, where the block is

```yaml
jobqueue:
  pbs:
    cores: 1
    interface: ext
    job-extra: []
    local-directory: /glade/derecho/scratch/mlevy
    log-directory: /glade/derecho/scratch/mlevy
    memory: 10GiB
    name: dask-worker
    processes: 1
    queue: regular
    resource-spec: select=1:ncpus=1:mem=10GB
    walltime: 01:00:00
```

and again, I've updated `log-directory` and `local-directory`.
